# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b88ad3593d467153548dafd0681de520df5c4b1f117ba8f1d372b617cd7d4cdadc37fcd2784a18b09d733c9c638a51237470abb09acbe83fe84b30c9dcab9c1

test:
  secret_key_base: 7d04fe02203065c9923f6312642380305c582e0007797cde9110860a1486aa3df3504c1598b9d2b8b76720e316d52b02ef661d7ae1b768345274c1b4a0c4e367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
